algo = input('digite algo ')
print(f'a classe primitiva dessa palavra é ',type(algo))
print(f'tem somente espaços?',algo.isspace())
print(f'tem somente numeros ?',algo.isnumeric())
print('é alfabetico?',algo.isalpha())
print('e alfa-numerico ?',algo.isalnum())
print('esta escrito em maiusculas?',algo.isupper())
print('esta escrito so em minuscula?',algo.islower())
print('esta capiatazizada:?',algo.istitle())